#!/usr/bin/bash

# kopii to copy files and folders in weird way
# Copyright (C) 2022 Jules Azad EMERY a.k.a. ethicnology
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

FILE=$HOME/.tp
ARG=$1
if [ -f "$FILE" ]; then
    if [ ! $ARG ]; then
        > $FILE
        echo "$PWD" >> $FILE
        DESTINATION=$(<$FILE)
        echo "Portal created in $DESTINATION, waiting for contents…"
        exit 1
    else
        DESTINATION=$(<$FILE)
        SOURCE="$PWD/$ARG"
        if [ -d $ARG ]; then
            cp -r $SOURCE $DESTINATION
            echo "Copying directory: $ARG"
            > $FILE
            exit 1
        elif [ -f $ARG ]; then
            echo "Copying file: $ARG"
            cp $SOURCE $DESTINATION
            > $FILE
            exit 1
        else
            echo "$ARG is not valid"
            exit 1
        fi
    fi    
else
    touch $FILE
fi